// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ShiftGears.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ShiftGears::ShiftGears(int gear): Command() {
    m_gear = gear;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shifter.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ShiftGears::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void ShiftGears::Execute() {

	if(m_gear == 0){
		Robot::shifter->ShifterOff();
	}
	else if (m_gear == 1){
		Robot::shifter->ShiftDown();
		printf("Shifted to low gear\n");
	}
	else if (m_gear == 2){
		Robot::shifter->ShiftUp();
		printf("shifted to high gear\n");

	}

}

// Make this return true when this Command no longer needs to run execute()
bool ShiftGears::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void ShiftGears::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShiftGears::Interrupted() {

}
